config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'posts#index'

resources :posts do
    resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  accepts_nested_attributes_for :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :load_post, :authenticate_user! only: [:new, :create, :destroy]

  
  def index
    @comments = @post.comments.all
    # @user = current_user
  end

  def show
    @comment = @post.comments.find(params[:id])
  end

  def new
    @comment = @post.comments.new

  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_comments_path(@post)
  end

  private
  def comment_params
    params[:comment].permit(:body)
  end

  def load_post
    @post = Post.find(params[:post_id])
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
    @posts = Post.all
      respond_to do |f|
        f.json { render :json => @posts, :only => [:id, :title, :author, :text]}
      end
    @user = current_user
end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    redirect_to @post
  end

private
  def post_params
    params[:post].permit(:body, :title, :comments_attributes=>[:body])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1><%= @post.title %></h1>
<!-- #why is the post title post #1? -->
<h2><%=@post.body%></h2>

	<div class="comments"><b>Comments:</b>
	<% @comments.each do |comment|%>
	  <li><%=comment.body%>
	  	<br>Comment by: <%=@user.email%>
	    <%#= link_to "Show", auction_bid_path(@auction, bid) %>
	    <%= link_to "Delete", [@post, comment], method: :delete, data: {confirm: "Are You Sure?"} %>
	  </li>
	<% end %>
	</div>
<br>

<div class="button">
	<%= link_to "Comment on this Post", new_post_comment_path(@post), :class=>"btn btn-info" %>
		</p>
	<%= link_to "Back to All Posts", posts_path(@post), :class=>"btn btn-info" %>
</div>

app/views/comments/new.html.erb
<h1>Create A New Comment</h1>

<%= form_for ([@post, @comment]) do |f| %>
  <%= f.text_field :body, placeholder: "Body" %>
  <%= f.submit %>

<% end %>

app/views/comments/show.html.erb
<h1>Comment Show Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
 <% end %>
 <% if alert %>
   <p class="alert alert-danger"><%= alert %></p>
 <% end %>
 <%= yield %>


</body>
</html>

app/views/posts/index.html.erb
<h1>Posts Index</h1>

<% @posts.each do |post| %>
<li><%= link_to post.title, post_comments_path(post) %></li>
<% end %>

app/views/posts/new.html.erb
<h1>Write New Post</h1>

<%=form_for @post do |f| %>
  <%= f.text_field :title, placeholder: "Name Of Post" %>
  <%= f.text_field :body, placeholder: "write post here" %>
 <!--  <%#= f.fields_for :comments, @post.comments.build do |b| %>
  <%#= b.text_field :body, placeholder: "write comment here" %> -->
  <%# end %>
  <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<h1>Post Show Page</h1>